export type DroneType = 'groundcraft' | 'aircraft' | 'medicart' | 'autodoc';

export interface Drone {
  id: string;
  name: string;
  description: string;
  type: DroneType;
  modSlots: number;
  moddingCapacity: number;
  sensor: number;
  hitpoints: number;
  abilityIds: string[];
}

export const kAllDrones: Drone[] = [
  {
    id: 'wise-eagle-owl',
    name: 'Мудрый филин',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 2,
    description:
      'Может перевозить 3 персонажей. Иммунитет ко всему холодному оружию и легкому огнестрельному. Тяжелая броня. 2 хита\n\nКласс: Воздушная техника\nТип: Вертолёт\nSensor: 8',
    abilityIds: ['drone-heli', 'drone-heavy'],
  },
  {
    id: 'falcon',
    name: 'Ясный сокол',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 11,
    hitpoints: 3,
    description:
      'Может перевозить 3 персонажей. Иммунитет ко всему холодному оружию и легкому огнестрельному. Тяжелая броня. 3 хита\n\nКласс: Воздушная техника\nТип: Вертолёт\nSensor: 11',
    abilityIds: ['drone-heli', 'drone-heavy'],
  },
  {
    id: 'white-eagle',
    name: 'Белый орел',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 14,
    hitpoints: 4,
    description:
      'Может перевозить 3 персонажей. Иммунитет ко всему холодному оружию и легкому огнестрельному. Тяжелая броня. 4 хита\n\nКласс: Воздушная техника\nТип: Вертолёт\nSensor: 14',
    abilityIds: ['drone-heli', 'drone-heavy'],
  },
  {
    id: 'berkut',
    name: 'Беркут',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 17,
    hitpoints: 4,
    description:
      'Может перевозить 3 персонажей. Иммунитет ко всему холодному оружию и легкому огнестрельному. Тяжелая броня. Может лечить на поле боя! 4 хита\n\nКласс: Воздушная техника\nТип: Вертолёт\nSensor: 17',
    abilityIds: ['drone-heli', 'drone-heavy', 'medcart-light-heal-1', 'medcart-light-heal-2', 'medcart-heavy-heal-1', 'drone-use-pills'],
  },
  {
    id: 'beetle',
    name: 'Жук',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 3,
    hitpoints: 1,
    description:
      'Видеокамера. Иммунитет ко всему холодному оружию и легкому огнестрельному. 1 хит.\n\nКласс: Воздушная техника\nТип: Коптер\nSensor: 3',
    abilityIds: ['drone-copter'],
  },
  {
    id: 'wasp',
    name: 'Оса',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 7,
    hitpoints: 2,
    description:
      'Видеокамера. Иммунитет ко всему холодному оружию и легкому огнестрельному.Видеокамера. Иммунитет ко всему холодному оружию и легкому огнестрельному. 2 хита\n\nКласс: Воздушная техника\nТип: Коптер\nSensor: 7',
    abilityIds: ['drone-copter'],
  },
  {
    id: 'scorge',
    name: 'Скордж',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 1,
    description:
      'Бадабум!  Иммунитет ко всему холодному оружию и легкому огнестрельному. Массовое поражение вокруг! 1 хит.\n\nКласс: Воздушная техника\nТип: Коптер-камикадзе\nSensor: 8',
    abilityIds: ['drone-kabuum'],
  },
  {
    id: 'huxley',
    name: 'Хаксли',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 6,
    hitpoints: 1,
    description:
      'Проектор голограмм. Иммунитет ко всему холодному оружию и легкому огнестрельному. 1 хит.\n\nКласс: Воздушная техника\nТип: Коптер-проектор\nSensor: 6',
    abilityIds: ['drone-project'],
  },
  {
    id: 'tool-autodoc-1',
    name: 'Пирогов',
    type: 'autodoc',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 4,
    hitpoints: 6,
    description:
      'Автодок Пирогов - классика в области стационарных комплексов. Возможности комплекса позволяют надёжно взаимодействовать с простыми имплантами, а так же лечить пациентов.\n\nКласс: Стационар\nТип: Автодок\nSensor: 4',
    abilityIds: ['auto-doc-screen', 'auto-doc-bonus-1', 'drone-heavy', 'drone-use-pills'],
  },
  {
    id: 'tool-autodoc-2',
    name: 'Авиценна',
    type: 'autodoc',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 6,
    description:
      'Автодок Авиценна - комплекс, который позволит взаимодействовать с продвинутыми имплантами.\n\nКласс: Стационар\nТип: Автодок\nSensor: 8',
    abilityIds: ['auto-doc-screen', 'auto-doc-bonus-3', 'drone-heavy', 'drone-use-pills', 'drone-whats-in-the-body'],
  },
  {
    id: 'tool-autodoc-3',
    name: 'Асклепий',
    type: 'autodoc',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 12,
    hitpoints: 6,
    description:
      'Асклепий - потрясающий автодок, в котором продвинутый Риггер сможет проводить достаточно сложные операции (если конечно разберется как с ним работать), ну а в руках мастера, автодок становится мощнейшим инструментом для операций с самыми сложными имплантами.\r\n\r\nКласс: Стационар\r\nТип: Автодок\r\nSensor: 12',
    abilityIds: ['auto-doc-screen', 'auto-doc-bonus-5', 'drone-heavy', 'drone-use-pills', 'drone-whats-in-the-body'],
  },
  {
    id: 'factory-1',
    name: 'Мастерская',
    type: 'autodoc',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 4,
    hitpoints: 6,
    description:
      'В этом дроне можно ремонтировать другие дроны и кибердеки, если они поломаны.\r\n\r\nКласс: Стационар\r\nТип: Мастерская\r\nSensor: 4',
    abilityIds: ['drone-recovery', 'cyberdeck-recovery', 'drone-heavy'],
  },
  {
    id: 'belarus',
    name: 'Беларусь',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 4,
    hitpoints: 2,
    description:
      'Дроны модели Беларусь появились давно, они просты в управлении, не очень надежны (2 хита), но могут служить Щитом, на них установлена Тяжелая броня.\n\nКласс: Техника\nТип: Бульдозер\nSensor: 4',
    abilityIds: ['drone-dozer', 'drone-heavy'],
  },
  {
    id: 'trici',
    name: 'Sweet Ginger Bulldozer',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 7,
    hitpoints: 3,
    description:
      'В дронах модели Sweet Ginger решили проблему надёжности (3 хита), но они стали чуть капризнее в управлении, могут служить надёжным Щитом, на них установлена Тяжелая броня.\n\nКласс: Техника\nТип: Бульдозер\nSensor: 7',
    abilityIds: ['drone-dozer', 'drone-heavy'],
  },
  {
    id: 'heemeyer',
    name: 'Химейер',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 11,
    hitpoints: 5,
    description:
      'Химейер передовая модель бульдозеров. Надежность на высоте (5 хитов), они служат мощным Щитом, с Тяжелой бронёй.\n\nКласс: Техника\nТип: Бульдозер\nSensor: 11',
    abilityIds: ['drone-dozer', 'drone-heavy'],
  },
  {
    id: 'dzerginsk',
    name: 'Дзержинский',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 7,
    hitpoints: 5,
    description: 'Всем стоять! Работает полиция! дрон может применить Паралич движения. 5 хитов\n\nКласс: Техника\nТип: Полицай\nSensor: 7',
    abilityIds: ['drone-paralysis-1'],
  },
  {
    id: 'trockiy',
    name: 'Троцкий',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 11,
    hitpoints: 3,
    description:
      'Всем стоять! Работает полиция! У дрона Тяжелая броня, может применить два Паралича движения. 3 хита\n\nКласс: Техника\nТип: Полицай\nSensor: 11',
    abilityIds: ['drone-paralysis-1', 'drone-paralysis-2', 'drone-heavy'],
  },
  {
    id: 'beriya',
    name: 'Берия',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 16,
    hitpoints: 4,
    description:
      'Всем стоять! Работает Робокоп! у дрона Тяжелая броня, пулемёт, может применить три Паралича движения. Обладает повышенной надёжностью (4 хита).\n\nКласс: Техника\nТип: Полицай\nSensor: 16',
    abilityIds: ['drone-paralysis-1', 'drone-paralysis-2', 'drone-paralysis-3', 'drone-heavy', 'drone-ekzo'],
  },
  {
    id: 'grom',
    name: 'Гром',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 6,
    hitpoints: 2,
    description: 'Пушка. 2 хита\n\nКласс: Техника\nТип: Турель\nSensor: 6',
    abilityIds: ['drone-turret'],
  },
  {
    id: 'cat',
    name: 'Кэт',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 3,
    description: 'Пушка. 3 хита\n\nКласс: Техника\nТип: Турель\nSensor: 8',
    abilityIds: ['drone-turret'],
  },
  {
    id: 'bfg',
    name: 'БФГ',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 11,
    hitpoints: 4,
    description: 'Пушка. 4 хита\r\n\r\nКласс: Техника\r\nТип: Турель\r\nSensor: 11',
    abilityIds: ['drone-turret'],
  },
  {
    id: 'marchal',
    name: 'Маршал',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 12,
    hitpoints: 4,
    description: 'Пулемет. Тяжелая броня. 4 хита.\r\n\r\nКласс: Техника\r\nТип: Экзоскелет\r\nSensor: 12',
    abilityIds: ['drone-ekzo', 'drone-heavy'],
  },
  {
    id: 'drednaught',
    name: 'Дредноут',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 3,
    description: 'Пулемет. Тяжелая броня. 3 хита.\n\nКласс: Техника\nТип: Экзоскелет\nSensor: 8',
    abilityIds: ['drone-ekzo', 'drone-heavy'],
  },
  {
    id: 'kosmos',
    name: 'Космос',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 18,
    hitpoints: 4,
    description: 'Пулемет. Тяжелая броня. 4 хита. Может лечить на поле боя!\n\nКласс: Техника\nТип: Экзоскелет\nSensor: 18',
    abilityIds: ['drone-ekzo', 'drone-heavy', 'medcart-light-heal-1', 'medcart-light-heal-2', 'medcart-heavy-heal-1'],
  },
  {
    id: 'pecheneg',
    name: 'Печенег',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 16,
    hitpoints: 5,
    description: 'Пулемет. Тяжелая броня. 5 хитов\r\n\r\nКласс: Техника\r\nТип: Экзоскелет\r\nSensor: 14',
    abilityIds: ['drone-ekzo', 'drone-heavy'],
  },
  {
    id: 'medicart',
    name: 'Медикарт',
    type: 'medicart',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 4,
    hitpoints: 3,
    description:
      'Медикарт. Простая модель, обладает 3 хитами, может лечить 2 легких ранения и 1 тяжёлое за раз.\n\nКласс: Поддержка\nТип: Медикарт\nSensor: 4',
    abilityIds: ['drone-medcart', 'medcart-light-heal-1', 'medcart-light-heal-2', 'medcart-heavy-heal-1'],
  },
  {
    id: 'hippocrates',
    name: 'Гиппократ',
    type: 'medicart',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 5,
    description:
      'Гиппократ это медикарт 2-го поколения, в нем усиленны возможности по лечению (2 легких и 2 тяжёлых за раз), и повышена надёжность (5 хитов)\n\nКласс: Поддержка\nТип: Медикарт\nSensor: 8',
    abilityIds: [
      'drone-medcart',
      'medcart-light-heal-1',
      'medcart-light-heal-2',
      'medcart-heavy-heal-1',
      'medcart-heavy-heal-2',
      'drone-use-pills',
    ],
  },
  {
    id: 'lekar',
    name: 'Лекарь',
    type: 'medicart',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 4,
    description:
      'Мечта группы силовой поддержки! Обладает возможностями Гиппократа  по лечению ( 2 легких и 2 тяжёлых за раз), но при этом на нём установлена Тяжёлая броня!\n\nКласс: Поддержка\nТип: Медикарт\nSensor: 8',
    abilityIds: [
      'drone-medcart',
      'medcart-light-heal-1',
      'medcart-light-heal-2',
      'medcart-heavy-heal-1',
      'medcart-heavy-heal-2',
      'drone-heavy',
      'drone-use-pills',
      'drone-whats-in-the-body',
    ],
  },
  {
    id: 'kuzhuget',
    name: 'Кужугет',
    type: 'medicart',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 12,
    hitpoints: 6,
    description:
      'Мечта группы поддержки, самый топчик по возможностям (3 легких и 3 тяжелых ранения за раз лечить можно), невероятно надёжный (6 хитов) и обладает возможностью реанимации прямо на поле боя!\n\nКласс: Поддержка\nТип: Медикарт\nSensor: 12',
    abilityIds: [
      'drone-medcart',
      'medcart-light-heal-1',
      'medcart-light-heal-2',
      'medcart-light-heal-3',
      'medcart-heavy-heal-1',
      'medcart-heavy-heal-2',
      'medcart-heavy-heal-3',
      'medcart-reanimate',
      'drone-use-pills',
      'drone-whats-in-the-body',
    ],
  },
  {
    id: 'konfuciy',
    name: 'Конфуций',
    type: 'medicart',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 18,
    hitpoints: 4,
    description:
      'Самый топовый медикарт, секретная экспериментальная модель, обладает полными известными возможностями по реанимации полным комплексом защиты и самообороны! (пулемет, тяжелая броня)\n\nКласс: Поддержка\nТип: Медикарт\nSensor: 18',
    abilityIds: [
      'drone-medcart',
      'medcart-light-heal-1',
      'medcart-light-heal-2',
      'medcart-light-heal-3',
      'medcart-heavy-heal-1',
      'medcart-heavy-heal-2',
      'medcart-heavy-heal-3',
      'medcart-reanimate',
      'drone-ekzo',
      'drone-heavy',
      'drone-use-pills',
      'drone-whats-in-the-body',
    ],
  },
];
export const kCommonDroneAbilityIds = ['drone-danger', 'drone-logoff', 'in-drone'];

export const kDroneDangerAbilityIds = new Set(kCommonDroneAbilityIds);
export const kDroneAbilityIds = new Set(kCommonDroneAbilityIds.concat(...kAllDrones.map((drone) => drone.abilityIds)));
