export type DroneType = 'groundcraft' | 'aircraft' | 'medicraft';

export interface Drone {
  id: string;
  name: string;
  description: string;
  type: DroneType;
  modSlots: number;
  moddingCapacity: number;
  sensor: number;
  hitpoints: number;
  abilityIds: string[];
}

export const kAllDrones: Drone[] = [
  {
    id: 'belarus',
    name: 'Беларусь',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 4,
    hitpoints: 2,
    description: 'Щит. Тяжелая броня.',
    abilityIds: ['drone-dozer'],
  },
  {
    id: 'trici',
    name: 'Трици',
    type: 'groundcraft',
    modSlots: 1,
    moddingCapacity: 1,
    sensor: 5,
    hitpoints: 2,
    description: 'Щит. Тяжелая броня.',
    abilityIds: ['drone-dozer'],
  },
  {
    id: 'heemeyer',
    name: 'Химейер',
    type: 'groundcraft',
    modSlots: 1,
    moddingCapacity: 2,
    sensor: 7,
    hitpoints: 4,
    description: 'Щит. Тяжелая броня.',
    abilityIds: ['drone-dozer'],
  },
  {
    id: 'grom',
    name: 'Гром',
    type: 'groundcraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 7,
    hitpoints: 2,
    description: 'Пушка. Легкая броня.',
    abilityIds: ['drone-turret'],
  },
  {
    id: 'cat',
    name: 'Кэт',
    type: 'groundcraft',
    modSlots: 1,
    moddingCapacity: 1,
    sensor: 8,
    hitpoints: 2,
    description: 'Пушка. Легкая броня.',
    abilityIds: ['drone-turret'],
  },
  {
    id: 'bfg',
    name: 'БФГ',
    type: 'groundcraft',
    modSlots: 1,
    moddingCapacity: 2,
    sensor: 11,
    hitpoints: 3,
    description: 'Пушка. Легкая броня.',
    abilityIds: ['drone-turret'],
  },
  {
    id: 'drednaught',
    name: 'Дредноут',
    type: 'groundcraft',
    modSlots: 1,
    moddingCapacity: 1,
    sensor: 11,
    hitpoints: 4,
    description: 'Пулемет. Тяжелая броня.',
    abilityIds: ['drone-ekzo'],
  },
  {
    id: 'marchal',
    name: 'Маршал',
    type: 'groundcraft',
    modSlots: 1,
    moddingCapacity: 2,
    sensor: 14,
    hitpoints: 5,
    description: 'Пулемет. Тяжелая броня.',
    abilityIds: ['drone-ekzo'],
  },
  {
    id: 'pecheneg',
    name: 'Печенег',
    type: 'groundcraft',
    modSlots: 2,
    moddingCapacity: 3,
    sensor: 14,
    hitpoints: 5,
    description: 'Пулемет. Тяжелая броня.',
    abilityIds: ['drone-ekzo'],
  },
  {
    id: 'beetle',
    name: 'Жук',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 2,
    hitpoints: 1,
    description: 'Видеокамера. Нет брони. Иммунитет ко всему холодному оружию и легкому огнестрельному.',
    abilityIds: ['drone-copter'],
  },
  {
    id: 'wasp',
    name: 'Оса',
    type: 'aircraft',
    modSlots: 1,
    moddingCapacity: 1,
    sensor: 5,
    hitpoints: 1,
    description: 'Видеокамера. Нет брони. Иммунитет ко всему холодному оружию и легкому огнестрельному.',
    abilityIds: ['drone-copter'],
  },
  {
    id: 'huxley',
    name: 'Хаксли',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 1,
    description: 'Проектор голограмм. Нет брони. Иммунитет ко всему холодному оружию и легкому огнестрельному.',
    abilityIds: ['drone-project'],
  },
  {
    id: 'scorge',
    name: 'Скордж',
    type: 'aircraft',
    modSlots: 0,
    moddingCapacity: 0,
    sensor: 8,
    hitpoints: 1,
    description: 'Бадабум! Нет брони. Иммунитет ко всему холодному оружию и легкому огнестрельному.',
    abilityIds: ['drone-kabuum'],
  },
  {
    id: 'wise-eagle-owl',
    name: 'Мудрый филин',
    type: 'aircraft',
    modSlots: 1,
    moddingCapacity: 1,
    sensor: 12,
    hitpoints: 4,
    description: 'Может перевозить 3 персонажей. Легкая броня. Иммунитет к холодному оружию.',
    abilityIds: ['drone-heli'],
  },
  {
    id: 'falcon',
    name: 'Ясный сокол',
    type: 'aircraft',
    modSlots: 1,
    moddingCapacity: 2,
    sensor: 14,
    hitpoints: 5,
    description: 'Может перевозить 3 персонажей. Легкая броня. Иммунитет к холодному оружию.',
    abilityIds: ['drone-heli'],
  },
  {
    id: 'white-eagle',
    name: 'Белый орел',
    type: 'aircraft',
    modSlots: 2,
    moddingCapacity: 3,
    sensor: 14,
    hitpoints: 5,
    description: 'Может перевозить 3 персонажей. Легкая броня. Иммунитет к холодному оружию.',
    abilityIds: ['drone-heli'],
  },
  {
    id: 'medicart',
    name: 'Медикарт',
    type: 'medicraft',
    modSlots: 1,
    moddingCapacity: 1,
    sensor: 4,
    hitpoints: 2,
    description: 'Медикарт. Легкая броня.',
    abilityIds: ['drone-medcart', 'medcart-light-heal-1', 'medcart-light-heal-2', 'medcart-heavy-heal-1'],
  },
  {
    id: 'hippocrates',
    name: 'Гиппократ',
    type: 'medicraft',
    modSlots: 1,
    moddingCapacity: 2,
    sensor: 8,
    hitpoints: 3,
    description: 'Медикарт. Легкая броня.',
    abilityIds: ['drone-medcart', 'medcart-light-heal-1', 'medcart-light-heal-2', 'medcart-heavy-heal-1', 'medcart-heavy-heal-2'],
  },
  {
    id: 'kuzhuget',
    name: 'Кужугет',
    type: 'medicraft',
    modSlots: 2,
    moddingCapacity: 3,
    sensor: 12,
    hitpoints: 4,
    description: 'Медикарт. Легкая броня.',
    abilityIds: [
      'drone-medcart',
      'medcart-light-heal-1',
      'medcart-light-heal-2',
      'medcart-light-heal-3',
      'medcart-heavy-heal-1',
      'medcart-heavy-heal-2',
      'medcart-heavy-heal-3',
      'medcart-reanimate',
    ],
  },
];

export const kCommonDroneAbilityIds = ['drone-danger', 'drone-logoff'];

export const kDroneAbilityIds = new Set(kCommonDroneAbilityIds.concat(...kAllDrones.map((drone) => drone.abilityIds)));
