export const kAllSprites = [
  { id: 'sprite-backdoor', name: 'Спрайт Бэкдор' },
  { id: 'sprite-keys', name: 'Спрайт "ключи"' },
  { id: 'sprite-water-walkers', name: 'Спрайт "кувшинки" ' },
  { id: 'sprite-pen-n-note', name: 'Спрайт "блокнот и карандаш"' },
  { id: 'sprite-balls', name: 'Спрайт "шарики"' },
  { id: 'sprite-rubber-glowes', name: 'Спрайт "перчатки"' },
  { id: 'sprite-racket', name: 'Спрайт "ракетка"' },
  { id: 'sprite-candy', name: 'Спрайт "конфетка"' },
  { id: 'sprite-pipe', name: 'Спрайт "труба"' },
  { id: 'sprite-armor-light', name: 'Спрайт "Легкий доспех"' },
  { id: 'sprite-armor-heavy', name: 'Спрайт  "Тяжелый доспех"' },
  { id: 'sprite-shield', name: 'Спрайт  "Щит"' },
  { id: 'sprite-sword-short', name: 'Спрайт  "Одноручный меч"' },
  { id: 'sprite-sword-twohanded', name: 'Спрайт  "Двуручный меч"' },
  { id: 'sprite-sword-short-doubled', name: 'Спрайт  "Два коротких меча"' },
  { id: 'sprite-initiative-sign', name: 'Спрайт  "Значок инициативы"' },
];
