export const kAllSprites = [
  { id: 'sprite-backdoor' },
  { id: 'sprite-keys' },
  { id: 'sprite-water-walkers' },
  { id: 'sprite-pen-n-note' },
  { id: 'sprite-balls' },
  { id: 'sprite-rubber-glowes' },
  { id: 'sprite-racket' },
  { id: 'sprite-candy' },
  { id: 'sprite-pipe' },
  { id: 'sprite-armor-light' },
  { id: 'sprite-armor-heavy' },
  { id: 'sprite-shield' },
  { id: 'sprite-sword-short' },
  { id: 'sprite-sword-twohanded' },
  { id: 'sprite-sword-short-doubled' },
  { id: 'sprite-initiative-sign' },
];
