import { Modifier } from '@sr2020/interface/models/alice-model-engine';
import { modifierFromEffect } from './util';
import {
  increaseMagic,
  increaseMaxHp,
  increaseMaxTimeInVr,
  increaseResonance,
  increaseFadingResistance,
  increaseMatrixHp,
  increaseBiofeedbackResistance,
} from './basic_effects';

export interface Implant {
  id: string;
  name: string;
  description: string;
  slot: 'body' | 'arm' | 'head' | 'rcc' | 'commlink';
  grade: 'alpha' | 'beta' | 'gamma' | 'delta' | 'bio';
  essenceCost: number;
  installDifficulty: number;
  modifiers: Modifier[];
}

// TODO(aeremin): Remove when proper implementations are provided for all implants
export const dummyModifier: Modifier = modifierFromEffect(increaseMagic, { amount: 0 });

export const kAllImplants: Implant[] = [
  {
    id: 'strong-bones-alpha',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'Имплант +2 хита, иммунитет к Легкому холодному и легкому дистанционному оружию. Можешь надевать лёгкую и тяжёлую броню',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-bones-beta',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'Имплант +2 хита, иммунитет к Легкому холодному и легкому дистанционному оружию. Можешь надевать лёгкую и тяжёлую броню',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-bones-gamma',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'Имплант +2 хита, иммунитет к Легкому холодному и легкому дистанционному оружию. Можешь надевать лёгкую и тяжёлую броню',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-bones-delta',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'Имплант +2 хита, иммунитет к Легкому холодному и легкому дистанционному оружию. Можешь надевать лёгкую и тяжёлую броню',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-bones-bio',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'Имплант +2 хита, иммунитет к Легкому холодному и легкому дистанционному оружию. Можешь надевать лёгкую и тяжёлую броню',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-back-alpha',
    name: 'крепкая спина',
    slot: 'body',
    description: 'Имплант +2 хита, снижение урона от тяжелого оружия. Можешь пользоваться лёгкой бронёй',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-back-beta',
    name: 'крепкая спина',
    slot: 'body',
    description: 'Имплант +2 хита, снижение урона от тяжелого оружия. Можешь пользоваться лёгкой бронёй',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-back-gamma',
    name: 'крепкая спина',
    slot: 'body',
    description: 'Имплант +2 хита, снижение урона от тяжелого оружия. Можешь пользоваться лёгкой бронёй',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-back-delta',
    name: 'крепкая спина',
    slot: 'body',
    description: 'Имплант +2 хита, снижение урона от тяжелого оружия. Можешь пользоваться лёгкой бронёй',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'strong-back-bio',
    name: 'крепкая спина',
    slot: 'body',
    description: 'Имплант +2 хита, снижение урона от тяжелого оружия. Можешь пользоваться лёгкой бронёй',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMaxHp, { amount: 2 })],
  },
  {
    id: 'cyber-hand-alpha',
    name: 'Кибер-рука',
    slot: 'arm',
    description: 'позволяет использовать автоматическое оружие',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [],
  },
  {
    id: 'cyber-hand-beta',
    name: 'Кибер-рука',
    slot: 'arm',
    description: 'позволяет использовать автоматическое оружие',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [],
  },
  {
    id: 'cyber-hand-gamma',
    name: 'Кибер-рука',
    slot: 'arm',
    description: 'позволяет использовать автоматическое оружие',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [],
  },
  {
    id: 'cyber-hand-delta',
    name: 'Кибер-рука',
    slot: 'arm',
    description: 'позволяет использовать автоматическое оружие',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [],
  },
  {
    id: 'cyber-hand-bio',
    name: 'Кибер-рука',
    slot: 'arm',
    description: 'позволяет использовать автоматическое оружие',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [],
  },
  {
    id: 'comm-link-alpha',
    name: 'коммлинк',
    slot: 'commlink',
    description: 'позволяет подключаться к матрице',
    grade: 'alpha',
    essenceCost: 0.1,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'comm-link-beta',
    name: 'коммлинк',
    slot: 'commlink',
    description: 'позволяет подключаться к матрице',
    grade: 'bio',
    essenceCost: 0,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'сerebellum-alpha',
    name: 'мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс (только для целей работы с контролем)\n',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseResonance, { amount: 2 })],
  },
  {
    id: 'сerebellum-beta',
    name: 'мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс (только для целей работы с контролем)\n',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseResonance, { amount: 2 })],
  },
  {
    id: 'сerebellum-gamma',
    name: 'мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс (только для целей работы с контролем)\n',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseResonance, { amount: 2 })],
  },
  {
    id: 'сerebellum-delta',
    name: 'мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс (только для целей работы с контролем)\n',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseResonance, { amount: 2 })],
  },
  {
    id: 'сerebellum-bio',
    name: 'мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс (только для целей работы с контролем)\n',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseResonance, { amount: 2 })],
  },
  {
    id: 'scratcher-alpha',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на [0].',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 0 })],
  },
  {
    id: 'scratcher-beta',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на [0].',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 0 })],
  },
  {
    id: 'scratcher-gamma',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на [0].',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 0 })],
  },
  {
    id: 'scratcher-delta',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на [0].',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 0 })],
  },
  {
    id: 'scratcher-bio',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на [0].',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 0 })],
  },
  {
    id: 'shaper-alpha',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на [0]',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 0 })],
  },
  {
    id: 'shaper-beta',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на [0]',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 0 })],
  },
  {
    id: 'shaper-bio',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на [0]',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 0 })],
  },
  {
    id: 'shaper-gamma',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на [0]',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 0 })],
  },
  {
    id: 'shaper-bio',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на [0]',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 0 })],
  },
  {
    id: 'condom-alpha',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-beta',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-gamma',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-delta',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-bio',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'backup-alpha',
    name: 'бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [],
  },
  {
    id: 'backup-beta',
    name: 'бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [],
  },
  {
    id: 'backup-gamma',
    name: 'бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [],
  },
  {
    id: 'backup-delta',
    name: 'бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [],
  },
  {
    id: 'backup-bio',
    name: 'бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [],
  },
  {
    id: 'auto-soft-1-alpha',
    name: 'автософт 1',
    slot: 'head',
    description: 'понижает сложность управления дроном на 2',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-1-beta',
    name: 'автософт 1',
    slot: 'head',
    description: 'понижает сложность управления дроном на 2',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-1-gamma',
    name: 'автософт 1',
    slot: 'head',
    description: 'понижает сложность управления дроном на 2',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-1-delta',
    name: 'автософт 1',
    slot: 'head',
    description: 'понижает сложность управления дроном на 2',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-1-bio',
    name: 'автософт 1',
    slot: 'head',
    description: 'понижает сложность управления дроном на 2',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-2-alpha',
    name: 'автософт 2',
    slot: 'head',
    description: 'понижает сложность управления дроном на 4',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-2-beta',
    name: 'автософт 2',
    slot: 'head',
    description: 'понижает сложность управления дроном на 4',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-2-gamma',
    name: 'автософт 2',
    slot: 'head',
    description: 'понижает сложность управления дроном на 4',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-2-delta',
    name: 'автософт 2',
    slot: 'head',
    description: 'понижает сложность управления дроном на 4',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-2-bio',
    name: 'автософт 2',
    slot: 'head',
    description: 'понижает сложность управления дроном на 4',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-3-alpha',
    name: 'автософт 3',
    slot: 'head',
    description: 'понижает сложность управления дроном на 8',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-3-beta',
    name: 'автософт 3',
    slot: 'head',
    description: 'понижает сложность управления дроном на 8',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-3-gamma',
    name: 'автософт 3',
    slot: 'head',
    description: 'понижает сложность управления дроном на 8',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-3-delta',
    name: 'автософт 3',
    slot: 'head',
    description: 'понижает сложность управления дроном на 8',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'auto-soft-3-bio',
    name: 'автософт 3',
    slot: 'head',
    description: 'понижает сложность управления дроном на 8',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'medkit-alpha',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'medkit-beta',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'medkit-gamma',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'medkit-delta',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'medkit-bio',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'rcc-alpha',
    name: 'RCC',
    slot: 'rcc',
    description: 'позволяет подключаться к дронам сложности 6',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'rcc-beta',
    name: 'RCC',
    slot: 'rcc',
    description: 'позволяет подключаться к дронам сложности 8',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'rcc-gamma',
    name: 'RCC',
    slot: 'rcc',
    description: 'позволяет подключаться к дронам сложности 10',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'rcc-delta',
    name: 'RCC',
    slot: 'rcc',
    description: 'позволяет подключаться к дронам сложности 12',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'rcc-bio',
    name: 'RCC',
    slot: 'rcc',
    description: 'позволяет подключаться к дронам сложности 14',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'under-oak-alpha',
    name: 'Поддубный',
    slot: 'body',
    description: 'добавляет +1 к параметру body',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'under-oak-beta',
    name: 'Поддубный',
    slot: 'body',
    description: 'добавляет +1 к параметру body',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'under-oak-gamma',
    name: 'Поддубный',
    slot: 'body',
    description: 'добавляет +1 к параметру body',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'under-oak-delta',
    name: 'Поддубный',
    slot: 'body',
    description: 'добавляет +1 к параметру body',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'under-oak-bio',
    name: 'Поддубный',
    slot: 'body',
    description: 'добавляет +1 к параметру body',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'neuroprocessor-alpha',
    name: 'нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int\n',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'neuroprocessor-beta',
    name: 'нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int\n',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'neuroprocessor-gamma',
    name: 'нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int\n',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'neuroprocessor-delta',
    name: 'нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int\n',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'neuroprocessor-bio',
    name: 'нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int\n',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
  {
    id: 'elbrus-alpha',
    name: 'Эльбрус',
    slot: 'body',
    description: 'Добавляет +1 матричный хит\n',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 1 })],
  },
  {
    id: 'elbrus-beta',
    name: 'Эльбрус',
    slot: 'body',
    description: 'Добавляет +1 матричный хит\n',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 1 })],
  },
  {
    id: 'elbrus-gamma',
    name: 'Эльбрус',
    slot: 'body',
    description: 'Добавляет +1 матричный хит\n',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 1 })],
  },
  {
    id: 'elbrus-delta',
    name: 'Эльбрус',
    slot: 'body',
    description: 'Добавляет +1 матричный хит\n',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 1 })],
  },
  {
    id: 'elbrus-bio',
    name: 'Эльбрус',
    slot: 'body',
    description: 'Добавляет +1 матричный хит\n',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 1 })],
  },
  {
    id: 'dreamcast-alpha',
    name: 'Dreamcast',
    slot: 'head',
    description: 'макс время в VR + 60 минут',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 60 })],
  },
  {
    id: 'dreamcast-beta',
    name: 'Dreamcast',
    slot: 'head',
    description: 'макс время в VR + 60 минут',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 60 })],
  },
  {
    id: 'dreamcast-gamma',
    name: 'Dreamcast',
    slot: 'head',
    description: 'макс время в VR + 60 минут',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 60 })],
  },
  {
    id: 'dreamcast-delta',
    name: 'Dreamcast',
    slot: 'head',
    description: 'макс время в VR + 60 минут',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 60 })],
  },
  {
    id: 'dreamcast-bio',
    name: 'Dreamcast',
    slot: 'head',
    description: 'макс время в VR + 60 минут',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 60 })],
  },
  {
    id: 'autopilot-alpha',
    name: 'Автопилот\n',
    slot: 'body',
    description: 'макс время в дроне + 15 минут\n',
    grade: 'alpha',
    essenceCost: 2,
    installDifficulty: 3,
    modifiers: [dummyModifier],
  },
  {
    id: 'autopilot-beta',
    name: 'Автопилот\n',
    slot: 'body',
    description: 'макс время в дроне + 15 минут\n',
    grade: 'beta',
    essenceCost: 1.5,
    installDifficulty: 4,
    modifiers: [dummyModifier],
  },
  {
    id: 'autopilot-gamma',
    name: 'Автопилот\n',
    slot: 'body',
    description: 'макс время в дроне + 15 минут\n',
    grade: 'gamma',
    essenceCost: 1.2,
    installDifficulty: 5,
    modifiers: [dummyModifier],
  },
  {
    id: 'autopilot-delta',
    name: 'Автопилот\n',
    slot: 'body',
    description: 'макс время в дроне + 15 минут\n',
    grade: 'delta',
    essenceCost: 1,
    installDifficulty: 6,
    modifiers: [dummyModifier],
  },
  {
    id: 'autopilot-bio',
    name: 'Автопилот\n',
    slot: 'body',
    description: 'макс время в дроне + 15 минут\n',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 7,
    modifiers: [dummyModifier],
  },
];
