import { Modifier } from '@alice/alice-common/models/alice-model-engine';
import { modifierFromEffect } from './util';
import {
  increaseBiofeedbackResistance,
  increaseBody,
  increaseConversionAttack,
  increaseConversionDataprocessing,
  increaseConversionFirewall,
  increaseConversionSleaze,
  increaseDroneCrafts,
  increaseFadingResistance,
  increaseIntelligence,
  increaseMatrixHp,
  increaseMaxDroneDifficulty,
  increaseMaxTimeInDrone,
  increaseMaxTimeInVr,
  increaseRepomanBonus,
  increaseResonanceForControl,
} from './basic_effects';
import {
  onBadassNanohiveInstall,
  onBadassNanohiveRemove,
  onHorizonNanohiveInstall,
  onHorizonNanohiveRemove,
  onKokkoroNanohiveInstall,
  onKokkoroNanohiveRemove,
  onKoshcgheiNanohiveInstall,
  onKoshcgheiNanohiveRemove,
} from '@alice/sr2020-model-engine/scripts/character/nanohives';
import { Implant } from '@alice/sr2020-common/models/common_definitions';

export const kReviveModifierId = 'medkit-revive-modifier';

function createReviveModifier(): Modifier {
  return { mID: kReviveModifierId, priority: Modifier.kDefaultPriority, enabled: true, effects: [] };
}

export const kAllImplants: Implant[] = [
  {
    id: 'strong-bones-alpha',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить тяжёлую броню',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [],
  },
  {
    id: 'strong-bones-beta',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить тяжёлую броню',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [],
  },
  {
    id: 'strong-bones-gamma',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить тяжёлую броню',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [],
  },
  {
    id: 'strong-bones-delta',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить тяжёлую броню',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [],
  },
  {
    id: 'strong-bones-bio',
    name: 'Усиленные кости',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить тяжёлую броню',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [],
  },
  {
    id: 'strong-back-alpha',
    name: 'Крепкая спина',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить лёгкую броню',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [],
  },
  {
    id: 'strong-back-beta',
    name: 'Крепкая спина',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить лёгкую броню',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [],
  },
  {
    id: 'strong-back-gamma',
    name: 'Крепкая спина',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить лёгкую броню',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [],
  },
  {
    id: 'strong-back-delta',
    name: 'Крепкая спина',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить лёгкую броню',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [],
  },
  {
    id: 'strong-back-bio',
    name: 'Крепкая спина',
    slot: 'body',
    description: 'С этим имплантом ты можешь носить лёгкую броню',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [],
  },
  {
    id: 'cyber-hand-alpha',
    name: 'Кибер-рука',
    slot: 'arm',
    description:
      'При наличии одного импланта и нужного навыка позволяет использовать любое легкое холодное одноручное оружие, а также винтовки и автоматы. \nПри наличии двух имплантов и нужного навыка позволяет использовать любое тяжелое холодное двуручное оружие, а так же пулемёты.',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [],
  },
  {
    id: 'cyber-hand-beta',
    name: 'Кибер-рука',
    slot: 'arm',
    description:
      'При наличии одного импланта и нужного навыка позволяет использовать любое легкое холодное одноручное оружие, а также винтовки и автоматы. \nПри наличии двух имплантов и нужного навыка позволяет использовать любое тяжелое холодное двуручное оружие, а так же пулемёты.',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [],
  },
  {
    id: 'cyber-hand-gamma',
    name: 'Кибер-рука',
    slot: 'arm',
    description:
      'При наличии одного импланта и нужного навыка позволяет использовать любое легкое холодное одноручное оружие, а также винтовки и автоматы. \nПри наличии двух имплантов и нужного навыка позволяет использовать любое тяжелое холодное двуручное оружие, а так же пулемёты.',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [],
  },
  {
    id: 'cyber-hand-delta',
    name: 'Кибер-рука',
    slot: 'arm',
    description:
      'При наличии одного импланта и нужного навыка позволяет использовать любое легкое холодное одноручное оружие, а также винтовки и автоматы. \nПри наличии двух имплантов и нужного навыка позволяет использовать любое тяжелое холодное двуручное оружие, а так же пулемёты.',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [],
  },
  {
    id: 'cyber-hand-bio',
    name: 'Кибер-рука',
    slot: 'arm',
    description:
      'При наличии одного импланта и нужного навыка позволяет использовать любое легкое холодное одноручное оружие, а также винтовки и автоматы. \nПри наличии двух имплантов и нужного навыка позволяет использовать любое тяжелое холодное двуручное оружие, а так же пулемёты.',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [],
  },
  {
    id: 'сerebellum-alpha',
    name: 'Мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс \n',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseResonanceForControl, { amount: 2 })],
  },
  {
    id: 'сerebellum-beta',
    name: 'Мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс \n',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseResonanceForControl, { amount: 2 })],
  },
  {
    id: 'сerebellum-gamma',
    name: 'Мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс \n',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseResonanceForControl, { amount: 2 })],
  },
  {
    id: 'сerebellum-delta',
    name: 'Мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс \n',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseResonanceForControl, { amount: 2 })],
  },
  {
    id: 'сerebellum-bio',
    name: 'Мозжечок',
    slot: 'head',
    description:
      'Твой мозг нужен тебе для настоящих дел. Тупую работу - надо можно сплавить тупой железяке. Пусть вкалывает!\nЭто небольшой квантовый процессор, подключенный напрямую к мозгу.\n\nВ среде техномантов иметь такой имплант - стыдно.\n\n[+2] Резонанс \n',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseResonanceForControl, { amount: 2 })],
  },
  {
    id: 'scratcher-alpha',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на 50.',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 50 })],
  },
  {
    id: 'scratcher-beta',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на 50.',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 50 })],
  },
  {
    id: 'scratcher-gamma',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на 50.',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 50 })],
  },
  {
    id: 'scratcher-delta',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на 50.',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 50 })],
  },
  {
    id: 'scratcher-bio',
    name: 'Чесалка',
    slot: 'head',
    description: 'Хитроумный имплант, который следит за состоянием мозга при работе в Основании. Повышает устойчивость к фейдингу на 50.',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseFadingResistance, { amount: 50 })],
  },
  {
    id: 'shaper-alpha',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на 10.',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 10 })],
  },
  {
    id: 'shaper-beta',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на 10.',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 10 })],
  },
  {
    id: 'shaper-gamma',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на 10.',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 10 })],
  },
  {
    id: 'shaper-delta',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на 10.',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 10 })],
  },
  {
    id: 'shaper-bio',
    name: 'Шейпер',
    slot: 'head',
    description:
      'Собственных сил никогда не бывает много, и подстраховаться всегда не грех. Этот несложный имплант образует дублирующий канал для данных матрицы, что повышает матричное состояние на 10.',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseMatrixHp, { amount: 10 })],
  },
  {
    id: 'condom-alpha',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейдж-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность при проводном подключении через дата-линк к хот-симе Матрицы, ценой значительной потери остроты ощущений. \nВ настоящий момент его снова облюбовали декеры, а остальным он интересен очень слабо.\n\nУменьшает вероятность травмы от биофидбека',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-beta',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейдж-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность при проводном подключении через дата-линк к хот-симе Матрицы, ценой значительной потери остроты ощущений. \nВ настоящий момент его снова облюбовали декеры, а остальным он интересен очень слабо.\n\nУменьшает вероятность травмы от биофидбека',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-gamma',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-delta',
    name: 'Гондон',
    slot: 'body',
    description:
     'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'condom-bio',
    name: 'Гондон',
    slot: 'body',
    description:
      'Официальное название этого импланта "Биофидбек-фильтр", но так его называют разве что вейд-слейвы на митингах в коворкингах. Его придумали много лет назад, чтобы повысить безопасность в хот-симе Матрицы, ценой значительной потери остроты ощущений.\n\n[+10%] устойчивость к биофидбеку',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseBiofeedbackResistance, { amount: 10 })],
  },
  {
    id: 'backup-alpha',
    name: 'Бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [],
  },
  {
    id: 'backup-beta',
    name: 'Бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [],
  },
  {
    id: 'backup-gamma',
    name: 'Бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [],
  },
  {
    id: 'backup-delta',
    name: 'Бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [],
  },
  {
    id: 'backup-bio',
    name: 'Бэкап',
    slot: 'head',
    description: 'Персонаж не забывает события перед КС',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [],
  },
  {
    id: 'auto-soft-alpha',
    name: 'Автософт',
    slot: 'head',
    description: 'Улучшает навыки управления дронами',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseDroneCrafts, { amount: 2 })],
  },
  {
    id: 'auto-soft-beta',
    name: 'Автософт',
    slot: 'head',
    description: 'Улучшает навыки управления дронами',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseDroneCrafts, { amount: 2 })],
  },
  {
    id: 'auto-soft-gamma',
    name: 'Автософт',
    slot: 'head',
    description: 'Улучшает навыки управления дронами',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseDroneCrafts, { amount: 2 })],
  },
  {
    id: 'auto-soft-delta',
    name: 'Автософт',
    slot: 'head',
    description: 'Улучшает навыки управления дронами',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseDroneCrafts, { amount: 2 })],
  },
  {
    id: 'auto-soft-bio',
    name: 'Автософт',
    slot: 'head',
    description: 'Улучшает навыки управления дронами',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseDroneCrafts, { amount: 2 })],
  },
  {
    id: 'medkit-alpha',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [createReviveModifier()],
  },
  {
    id: 'medkit-beta',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [createReviveModifier()],
  },
  {
    id: 'medkit-gamma',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [createReviveModifier()],
  },
  {
    id: 'medkit-delta',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [createReviveModifier()],
  },
  {
    id: 'medkit-bio',
    name: 'MedKit',
    slot: 'body',
    description:
      'Выводит из состояния "тяжран" хозяина импланта через 10 минут после получения статуса, если он не был снят раньше другими способами. CD импланта 4 часа. ',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [createReviveModifier()],
  },
  {
    id: 'rcc-alpha',
    name: 'RCC',
    slot: 'rcc',
    description: 'Позволяет подключаться к дронам. EoS 6',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMaxDroneDifficulty, { amount: 1006 })],
  },
  {
    id: 'rcc-beta',
    name: 'RCC',
    slot: 'rcc',
    description: 'Позволяет подключаться к дронам. EoS 10',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseMaxDroneDifficulty, { amount: 1010 })],
  },
  {
    id: 'rcc-gamma',
    name: 'RCC',
    slot: 'rcc',
    description: 'Позволяет подключаться к дронам. EoS 14',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseMaxDroneDifficulty, { amount: 1014 })],
  },
  {
    id: 'rcc-delta',
    name: 'RCC',
    slot: 'rcc',
    description: 'Позволяет подключаться к дронам. EoS 19',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseMaxDroneDifficulty, { amount: 1019 })],
  },
  {
    id: 'rcc-bio',
    name: 'RCC',
    slot: 'rcc',
    description: 'Позволяет подключаться к дронам. EoS 19',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseMaxDroneDifficulty, { amount: 1019 })],
  },
  {
    id: 'under-oak-alpha',
    name: 'Поддубный',
    slot: 'body',
    description: 'Добавляет +1 к параметру body',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseBody, { amount: 1 })],
  },
  {
    id: 'under-oak-beta',
    name: 'Поддубный',
    slot: 'body',
    description: 'Добавляет +1 к параметру body',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseBody, { amount: 1 })],
  },
  {
    id: 'under-oak-gamma',
    name: 'Поддубный',
    slot: 'body',
    description: 'Добавляет +1 к параметру body',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseBody, { amount: 1 })],
  },
  {
    id: 'under-oak-delta',
    name: 'Поддубный',
    slot: 'body',
    description: 'Добавляет +1 к параметру body',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseBody, { amount: 1 })],
  },
  {
    id: 'under-oak-bio',
    name: 'Поддубный',
    slot: 'body',
    description: 'Добавляет +1 к параметру body',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseBody, { amount: 1 })],
  },
  {
    id: 'neuroprocessor-alpha',
    name: 'Нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseIntelligence, { amount: 1 })],
  },
  {
    id: 'neuroprocessor-beta',
    name: 'Нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseIntelligence, { amount: 1 })],
  },
  {
    id: 'neuroprocessor-gamma',
    name: 'Нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseIntelligence, { amount: 1 })],
  },
  {
    id: 'neuroprocessor-delta',
    name: 'Нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseIntelligence, { amount: 1 })],
  },
  {
    id: 'neuroprocessor-bio',
    name: 'Нейропроцессор',
    slot: 'head',
    description: 'Добавляет +1 к параметру int',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseIntelligence, { amount: 1 })],
  },
  {
    id: 'elbrus-alpha',
    name: 'Эльбрус',
    slot: 'arm',
    description: 'Добавляет +10% конверсия датапроцессинг',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseConversionDataprocessing, { amount: 10 })],
  },
  {
    id: 'elbrus-beta',
    name: 'Эльбрус',
    slot: 'arm',
    description: 'Добавляет +10% конверсия датапроцессинг',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseConversionDataprocessing, { amount: 1 })],
  },
  {
    id: 'elbrus-gamma',
    name: 'Эльбрус',
    slot: 'arm',
    description: 'Добавляет +10% конверсия датапроцессинг\n',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseConversionDataprocessing, { amount: 10 })],
  },
  {
    id: 'elbrus-delta',
    name: 'Эльбрус',
    slot: 'arm',
    description: 'Добавляет +10% конверсия датапроцессинг',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseConversionDataprocessing, { amount: 10 })],
  },
  {
    id: 'elbrus-bio',
    name: 'Эльбрус',
    slot: 'arm',
    description: 'Добавляет +10% конверсия датапроцессинг',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseConversionDataprocessing, { amount: 10 })],
  },
  {
    id: 'goblin-alpha',
    name: 'Гоблин',
    slot: 'arm',
    description: 'Добавляет +10% конверсии sleaze',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseConversionSleaze, { amount: 10 })],
  },
  {
    id: 'goblin-beta',
    name: 'Гоблин',
    slot: 'arm',
    description: 'Добавляет +10% конверсии sleaze',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseConversionSleaze, { amount: 10 })],
  },
  {
    id: 'goblin-gamma',
    name: 'Гоблин',
    slot: 'arm',
    description: 'Добавляет +10% конверсии sleaze',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseConversionSleaze, { amount: 10 })],
  },
  {
    id: 'goblin-delta',
    name: 'Гоблин',
    slot: 'arm',
    description: 'Добавляет +10% конверсии sleaze',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseConversionSleaze, { amount: 10 })],
  },
  {
    id: 'goblin-bio',
    name: 'Гоблин',
    slot: 'arm',
    description: 'Добавляет +10% конверсии sleaze',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseConversionSleaze, { amount: 10 })],
  },
  {
    id: 'kunai-alpha',
    name: 'Кунай',
    slot: 'arm',
    description: 'Добавляет +10% конверсии attack',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseConversionAttack, { amount: 10 })],
  },
  {
    id: 'kunai-beta',
    name: 'Кунай',
    slot: 'arm',
    description: 'Добавляет +10% конверсии attack',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseConversionAttack, { amount: 10 })],
  },
  {
    id: 'kunai-gamma',
    name: 'Кунай',
    slot: 'arm',
    description: 'Добавляет +10% конверсии attack',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseConversionAttack, { amount: 10 })],
  },
  {
    id: 'kunai-delta',
    name: 'Кунай',
    slot: 'arm',
    description: 'Добавляет +10% конверсии attack',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseConversionAttack, { amount: 10 })],
  },
  {
    id: 'kunai-bio',
    name: 'Кунай',
    slot: 'arm',
    description: 'Добавляет +10% конверсии attack',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseConversionAttack, { amount: 10 })],
  },
  {
    id: 'geffen-alpha',
    name: 'Геффен',
    slot: 'arm',
    description: 'Добавляет +10% конверсии firewall',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseConversionFirewall, { amount: 10 })],
  },
  {
    id: 'geffen-beta',
    name: 'Геффен',
    slot: 'arm',
    description: 'Добавляет +10% конверсии firewall',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseConversionFirewall, { amount: 10 })],
  },
  {
    id: 'geffen-gamma',
    name: 'Геффен',
    slot: 'arm',
    description: 'Добавляет +10% конверсии firewall',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseConversionFirewall, { amount: 10 })],
  },
  {
    id: 'geffen-delta',
    name: 'Геффен',
    slot: 'arm',
    description: 'Добавляет +10% конверсии firewall',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseConversionFirewall, { amount: 10 })],
  },
  {
    id: 'geffen-bio',
    name: 'Геффен',
    slot: 'arm',
    description: 'Добавляет +10% конверсии firewall',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseConversionFirewall, { amount: 10 })],
  },
  {
    id: 'dreamcast-alpha',
    name: 'Dreamcast',
    slot: 'head',
    description: 'Макс время в VR +30 минут',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 30 })],
  },
  {
    id: 'dreamcast-beta',
    name: 'Dreamcast',
    slot: 'head',
    description: 'Макс время в VR +30 минут',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 30 })],
  },
  {
    id: 'dreamcast-gamma',
    name: 'Dreamcast',
    slot: 'head',
    description: 'Макс время в VR +30 минут',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 30 })],
  },
  {
    id: 'dreamcast-delta',
    name: 'Dreamcast',
    slot: 'head',
    description: 'Макс время в VR +30 минут',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 30 })],
  },
  {
    id: 'dreamcast-bio',
    name: 'Dreamcast',
    slot: 'head',
    description: 'Макс время в VR +30 минут',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseMaxTimeInVr, { amount: 30 })],
  },
  {
    id: 'autopilot-alpha',
    name: 'Автопилот',
    slot: 'body',
    description: 'Макс время в дроне +15 минут',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseMaxTimeInDrone, { amount: 15 })],
  },
  {
    id: 'autopilot-beta',
    name: 'Автопилот',
    slot: 'body',
    description: 'Макс время в дроне +15 минут',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseMaxTimeInDrone, { amount: 15 })],
  },
  {
    id: 'autopilot-gamma',
    name: 'Автопилот',
    slot: 'body',
    description: 'Макс время в дроне +15 минут',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseMaxTimeInDrone, { amount: 15 })],
  },
  {
    id: 'autopilot-delta',
    name: 'Автопилот',
    slot: 'body',
    description: 'Макс время в дроне +15 минут',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseMaxTimeInDrone, { amount: 15 })],
  },
  {
    id: 'autopilot-bio',
    name: 'Автопилот',
    slot: 'body',
    description: 'Макс время в дроне + 15 минут',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseMaxTimeInDrone, { amount: 15 })],
  },
  {
    id: 'stayer-alpha',
    name: 'Стайер',
    slot: 'body',
    description: 'Даёт +10 минут подключения к деке',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [],
  },
  {
    id: 'stayer-beta',
    name: 'Стайер',
    slot: 'body',
    description: 'Даёт +10 минут подключения к деке',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [],
  },
  {
    id: 'stayer-gamma',
    name: 'Стайер',
    slot: 'body',
    description: 'Даёт +10 минут подключения к деке',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [],
  },
  {
    id: 'stayer-delta',
    name: 'Стайер',
    slot: 'body',
    description: 'Даёт +10 минут подключения к деке',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [],
  },
  {
    id: 'stayer-bio',
    name: 'Стайер',
    slot: 'body',
    description: 'Даёт +10 минут подключения к деке',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [],
  },
  {
    id: 'leatherman-alpha',
    name: 'Лезерман',
    slot: 'arm',
    description: 'С таким набором инструментов в руке гораздо сподручнее вырезать импланты',
    grade: 'alpha',
    essenceCost: 1.5,
    installDifficulty: 7,
    modifiers: [modifierFromEffect(increaseRepomanBonus, { amount: 2 })],
  },
  {
    id: 'leatherman-beta',
    name: 'Лезерман',
    slot: 'arm',
    description: 'С таким набором инструментов в руке гораздо сподручнее вырезать импланты',
    grade: 'beta',
    essenceCost: 1.2,
    installDifficulty: 9,
    modifiers: [modifierFromEffect(increaseRepomanBonus, { amount: 2 })],
  },
  {
    id: 'leatherman-gamma',
    name: 'Лезерман',
    slot: 'arm',
    description: 'С таким набором инструментов в руке гораздо сподручнее вырезать импланты',
    grade: 'gamma',
    essenceCost: 0.9,
    installDifficulty: 11,
    modifiers: [modifierFromEffect(increaseRepomanBonus, { amount: 2 })],
  },
  {
    id: 'leatherman-delta',
    name: 'Лезерман',
    slot: 'arm',
    description: 'С таким набором инструментов в руке гораздо сподручнее вырезать импланты',
    grade: 'delta',
    essenceCost: 0.6,
    installDifficulty: 15,
    modifiers: [modifierFromEffect(increaseRepomanBonus, { amount: 2 })],
  },
  {
    id: 'leatherman-bio',
    name: 'Лезерман',
    slot: 'arm',
    description: 'С таким набором инструментов в руке гораздо сподручнее вырезать импланты',
    grade: 'bio',
    essenceCost: 0.3,
    installDifficulty: 21,
    modifiers: [modifierFromEffect(increaseRepomanBonus, { amount: 2 })],
  },
  //spesial implants
  {
    id: 'scalp-bio',
    name: 'Косметический скальп',
    slot: 'head',
    description: 'Биоактивные подкожные энзимы навсегда избавляют тебя от перхоти',
    grade: 'bio',
    essenceCost: 0.1,
    installDifficulty: 16,
    modifiers: [],
  },
  {
    id: 'viscera-bio',
    name: 'Улучшенные органы',
    slot: 'body',
    description: 'Пересаженные генномодифицированные внутренние органы, с генами акул, ящериц и т.п. снидают риск рака, инфаркта, инсульта на 90%\n',
    grade: 'bio',
    essenceCost: 0.5,
    installDifficulty: 20,
    modifiers: [],
  },
  {
    id: 'white-romb-head-bio',
    name: 'Белый ромб во лбу',
    slot: 'head',
    description: 'Твоя кожа всегда в прекрасном состоянии',
    grade: 'bio',
    essenceCost: 0.2,
    installDifficulty: 21,
    modifiers: [],
  },
  {
    id: 'white-romb-body-bio',
    name: 'Белый ромб на грудь',
    slot: 'body',
    description: 'Твоя фигура бесподобна',
    grade: 'bio',
    essenceCost: 0.2,
    installDifficulty: 21,
    modifiers: [],
  },
  {
    id: 'white-romb-hand-bio',
    name: 'Белый ромб в ладошку',
    slot: 'arm',
    description: 'Твои руки изящны',
    grade: 'bio',
    essenceCost: 0.2,
    installDifficulty: 21,
    modifiers: [],
  },
  //nanohive
  {
    id: 'nanohive-kokkoro-1',
    name: ' Properly Organised Resources Nothern hub',
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'delta',
    essenceCost: 0.9,
    installDifficulty: 15,
    modifiers: [],
    onInstallEvent: onKokkoroNanohiveInstall.name,
    onRemoveEvent: onKokkoroNanohiveRemove.name,
  },
  {
    id: 'nanohive-koshchej-1',
    name: 'EIS_neurointerface',
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'delta',
    essenceCost: 0.9,
    installDifficulty: 15,
    modifiers: [],
    onInstallEvent: onKoshcgheiNanohiveInstall.name,
    onRemoveEvent: onKoshcgheiNanohiveRemove.name,
  },
  {
    id: 'nanohive-horizon-1',
    name: "Heaven's_key_mod",
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'delta',
    essenceCost: 0.9,
    installDifficulty: 15,
    modifiers: [],
    onInstallEvent: onHorizonNanohiveInstall.name,
    onRemoveEvent: onHorizonNanohiveRemove.name,
  },
  {
    id: 'nanohive-badass-1',
    name: 'MindP_datanalyst',
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'delta',
    essenceCost: 0.9,
    installDifficulty: 15,
    modifiers: [],
    onInstallEvent: onBadassNanohiveInstall.name,
    onRemoveEvent: onBadassNanohiveRemove.name,
  },
  {
    id: 'nanohive-kokkoro-2',
    name: 'GLaDOS central core',
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'beta',
    essenceCost: 1,
    installDifficulty: 9,
    modifiers: [],
    onInstallEvent: onKokkoroNanohiveInstall.name,
    onRemoveEvent: onKokkoroNanohiveRemove.name,
  },
  {
    id: 'nanohive-koshchej-2',
    name: 'ESG_neurointerface',
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'beta',
    essenceCost: 1,
    installDifficulty: 9,
    modifiers: [],
    onInstallEvent: onKoshcgheiNanohiveInstall.name,
    onRemoveEvent: onKoshcgheiNanohiveRemove.name,
  },
  {
    id: 'nanohive-horizon-2',
    name: 'SofAlphaeus_mod',
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'beta',
    essenceCost: 1,
    installDifficulty: 9,
    modifiers: [],
    onInstallEvent: onHorizonNanohiveInstall.name,
    onRemoveEvent: onHorizonNanohiveRemove.name,
  },
  {
    id: 'nanohive-badass-2',
    name: 'AoF System',
    slot: 'body',
    description:
      '- У тебя появилась активная абилка "Стрелок". Нажав кнопку ты можешь использовать автоматическое оружие 15 минут\n- У тебя появилась активная абилка "Здоровяк". Нажав кнопку, ты получаешь +2 хита на 15 минут\n- У тебя появилась активная абилка "Бэкап". Ты можешь забыть эпизод, если напишешь о нем Искусственному Интеллекту используя мессенджеры или расскажешь лично. Только в личном присутствии этого Искусственного Интеллекта ты помнишь все забытые таким образом эпизоды.\n- У тебя появилась активная абилка "Нано-подключение к VR". При подключении к VR в течение 40 минут, время пребывания там увеличено на час.',
    grade: 'beta',
    essenceCost: 1,
    installDifficulty: 9,
    modifiers: [],
    onInstallEvent: onBadassNanohiveInstall.name,
    onRemoveEvent: onBadassNanohiveRemove.name,
  },
];
